[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm install -g pnpm@10.4.1', 'pnpm config set store-dir /tmp/pnpm-store', 'pnpm install --no-frozen-lockfile --prefer-offline']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'
