services:
  - type: web
    name: websitekua
    runtime: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_APP_ID
        value: websitekua
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: kua-pecalungan-secret-key-2024
